### PR TITLE
site UI improvements

### PR DESCRIPTION
**Pull request by yomed**
First step in trying to consolidate and improve the site UI. Notable changes are:
-bolder headings, no longer red/purple
-spacing adjustments for docs and posts
-removed third col on homepage (this sort of copy should still be used somewhere, but not along with the other columns here).
-removed "learn more" links on homepage, made heading links more obvious (blue)
-made consistent use of light gray #777

Let me know what you think!

screen shot 2015-10-10 at 4 00 21 pm
screen shot 2015-10-10 at 4 00 24 pm
screen shot 2015-10-10 at 4 00 16 pm

### CODE REVIEW

**Comment by patrick-steele-idem** [comment]
Thanks for the improvements @yomed. I agree with all of your changes except for the removal of the third column. I think the third column is needed for aesthetics...if you don't like the text for the column then I think we should experiment with alternative content/text. What do you think?

**Comment by philidem** [comment]
I agree about keeping the third column purely for aesthetics. The content in the third column was kind of awkward so maybe we can come up with something better.

How about code sample for the third column? It would need to be short and sweet, but I like the idea of giving people some idea of what a Marko template looks like.

**Comment by philidem** [comment]
I'm going to go ahead and merge this in but try some different alternatives for the third column.

**Comment by yomed** [comment]
Yeah, I agree the a third column makes sense aesthetically. It just seemed like it didn't fit in with the other two, which are both links to repos in the ecosystem. Let me think about how to improve it...

**Comment by yomed** [comment]
Maybe we should change those columns to marketing blurbs, and then have separate sections below which give a taste of marko and marko widgets.

**Pull request merged**
