### PR TITLE
Minor changes to make two columns look better

### PR DESCRIPTION
**Pull request by philidem**

### CODE REVIEW

**Comment by philidem** [comment]
These were minor tweaks to make two columns look a little better.
- Justify text within the "marketing" columns
- Center h3 in marketing column
- Change heading to: **Marko: HTML Templating**
- Changing heading to: **Marko Widgets: UI Components**

**Comment by philidem** [comment]
@yomed please let me know what you think.

**Comment by yomed** [comment]
Cool, I think this makes sense in the mean time. Btw, I don't think anybody supports `text-justify`.

**Comment by philidem** [comment]
You're right about `text-justify`... I shouldn't have read w3schools so quickly (man that site is bad...)

**Comment by patrick-steele-idem** [comment]
I'm not sure how I feel about the header prefixes (i.e. "Marko: " and "Marko Widgets: "). I also think the headers should still be left aligned.

**Pull request merged**
