### PR TITLE
simplify header and update homepage

### PR DESCRIPTION
**Pull request by yomed**
I've updated the homepage with a larger logo, and with a white background for the hero section. This helps reduce the number of colors (which I'll look into standardizing more later). 

For the header - I removed the fancy mobile menu and simplified the layout instead. It was a cool feature, but I think the simplicity should make interaction easier. In doing this I also removed the search form. Few sites have this - if it feels necessary, we should probably work on improving general navigation instead. Let me know what you think.

### CODE REVIEW

**Comment by patrick-steele-idem** [comment]
Hi @yomed,  thanks for the improvements! I was worried that the global nav might get larger over time but I think we will be okay. I will be adding the "Blog" link back soon (the first blog posts are almost ready). I do think the search is helpful, but I think we should just put a magnifying glass icon that when clicked on will open a search form. I think there is just enough room to include the "Blog" link and a magnifying glass so I am good with you removing the fancy menu :) I will merge in your changes now.

Thoughts on the search icon?

**Comment by yomed** [comment]
Ok sure, I can bring search back as an icon. Will probably need to make some adjustments at the smallest sizes (around 320), but I think it should work. I can touch it up and send a new PR tonight if you are merging this one now.

**Comment by patrick-steele-idem** [comment]
I have published your changes. If you can add a search icon that would be very helpful. I'm going to be working on improving the UI for [Try Marko Widgets Online](http://markojs.com/marko-widgets/try-online/) (I'm not liking the separate left and top nav).

**Comment by yomed** [comment]
Sounds good. Would you be ok with removing the home link, and rely on the direct/seo traffic + the header logo for that page?

**Comment by patrick-steele-idem** [comment]
I'm not opposed to removing the "Home" link. I think that makes sense.

**Pull request merged**
